"""initial schema

Revision ID: 3ce479b316bc
Revises: 
Create Date: 2026-09-12 15:22:45.393581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ce479b316bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment_type',
    sa.Column('ef_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ef_code')
    )
    op.create_table('equipment',
    sa.Column('equipment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('factory_code', sa.String(length=10), nullable=False),
    sa.Column('ef_code', sa.String(length=10), nullable=False),
    sa.Column('transformer_name', sa.String(length=50), nullable=False),
    sa.Column('voltage', sa.Integer(), nullable=False),
    sa.Column('onan_val', sa.Integer(), nullable=False),
    sa.Column('onaf_val', sa.Float(), nullable=False),
    sa.Column('operation_start_time', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ef_code'], ['equipment_type.ef_code'], ),
    sa.PrimaryKeyConstraint('equipment_id'),
    sa.UniqueConstraint('factory_code', 'ef_code', 'transformer_name', name='uq_equipment_natural_key')
    )
    op.create_table('design_attribute',
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.Column('fire_vul_type', sa.String(length=20), nullable=False),
    sa.Column('fire_spread_loc', sa.String(length=20), nullable=False),
    sa.Column('emerge_response_1s', sa.String(length=20), nullable=False),
    sa.Column('redundancy', sa.String(length=20), nullable=False),
    sa.Column('ato', sa.String(length=20), nullable=False),
    sa.Column('online_og_chk', sa.String(length=20), nullable=False),
    sa.Column('offline_safety_chk', sa.String(length=20), nullable=False),
    sa.Column('sec_num', sa.Integer(), nullable=False),
    sa.Column('alarm_num', sa.Integer(), nullable=False),
    sa.Column('insul_1st_lvup', sa.String(length=20), nullable=False),
    sa.Column('high_insul_adt', sa.String(length=20), nullable=False),
    sa.Column('double_insul', sa.String(length=20), nullable=False),
    sa.Column('install_55k', sa.String(length=20), nullable=False),
    sa.Column('sfra_test', sa.String(length=20), nullable=False),
    sa.Column('rip_install', sa.String(length=20), nullable=False),
    sa.Column('vacuum_set', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ),
    sa.PrimaryKeyConstraint('equipment_id')
    )
    op.create_table('dga_reading',
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('diag_time', sa.Date(), nullable=False),
    sa.Column('dga_h2', sa.Integer(), nullable=False),
    sa.Column('dga_c2h2', sa.Float(), nullable=False),
    sa.Column('dga_c2h4', sa.Integer(), nullable=False),
    sa.Column('dga_c2h6', sa.Integer(), nullable=False),
    sa.Column('dga_ch4', sa.Integer(), nullable=False),
    sa.Column('dga_c3h8', sa.Integer(), nullable=False),
    sa.Column('dga_co', sa.Integer(), nullable=False),
    sa.Column('dga_co2', sa.Integer(), nullable=False),
    sa.Column('dga_o2', sa.Integer(), nullable=False),
    sa.Column('dga_n2', sa.Integer(), nullable=False),
    sa.Column('dga_fluc', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ),
    sa.PrimaryKeyConstraint('equipment_id')
    )
    op.create_table('dielectric_test',
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.Date(), nullable=False),
    sa.Column('dielec_str_te_1', sa.Float(), nullable=False),
    sa.Column('dielec_str_te_2', sa.Float(), nullable=False),
    sa.Column('dielec_str_te_3', sa.Float(), nullable=False),
    sa.Column('dielec_str_te_4', sa.Float(), nullable=False),
    sa.Column('dielec_str_te_5', sa.Float(), nullable=False),
    sa.Column('dielec_str_te_6', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ),
    sa.PrimaryKeyConstraint('equipment_id')
    )
    op.create_table('equipment_extra_attribute',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('column_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.Column('inferred_type', sa.String(length=20), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('furan_reading',
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('diag_time', sa.Date(), nullable=False),
    sa.Column('furan_5h2f', sa.Integer(), nullable=False),
    sa.Column('furan_2fol', sa.Float(), nullable=False),
    sa.Column('furan_2fal', sa.Integer(), nullable=False),
    sa.Column('furan_2acf', sa.Integer(), nullable=False),
    sa.Column('furan_5m2f', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ),
    sa.PrimaryKeyConstraint('equipment_id')
    )
    op.create_table('load_condition',
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.Date(), nullable=False),
    sa.Column('load_percent', sa.Float(), nullable=False),
    sa.Column('coil_max_temp', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ),
    sa.PrimaryKeyConstraint('equipment_id')
    )
    op.create_table('oil_test',
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.Date(), nullable=False),
    sa.Column('acid_measure_val', sa.Float(), nullable=False),
    sa.Column('moisture_rslt', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ),
    sa.PrimaryKeyConstraint('equipment_id')
    )
    op.create_table('periodic_inspection',
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('measured_at', sa.Date(), nullable=False),
    sa.Column('part_discharge_diag', sa.String(length=20), nullable=False),
    sa.Column('oltc_96t_diag', sa.String(length=20), nullable=False),
    sa.Column('oltc_rslt', sa.Integer(), nullable=False),
    sa.Column('oltc_type', sa.String(length=20), nullable=False),
    sa.Column('thermal_img_temp', sa.String(length=20), nullable=False),
    sa.Column('noise_diag', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ),
    sa.PrimaryKeyConstraint('equipment_id')
    )
    op.create_table('score_snapshot',
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('pof_minus', sa.Integer(), nullable=False),
    sa.Column('pof', sa.Integer(), nullable=False),
    sa.Column('cof_minus', sa.Integer(), nullable=False),
    sa.Column('cof', sa.Integer(), nullable=False),
    sa.Column('dof_minus', sa.Integer(), nullable=False),
    sa.Column('dof', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ),
    sa.PrimaryKeyConstraint('equipment_id')
    )
    op.create_table('transformer_score_detail',
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('today', sa.Date(), nullable=False),
    sa.Column('operation_year', sa.Float(), nullable=False),
    sa.Column('age_minus', sa.Integer(), nullable=False),
    sa.Column('dga_tcg', sa.Float(), nullable=False),
    sa.Column('dga_diag', sa.String(length=20), nullable=False),
    sa.Column('dga_minus', sa.Integer(), nullable=False),
    sa.Column('load_minus', sa.Integer(), nullable=False),
    sa.Column('temp_minus', sa.Integer(), nullable=False),
    sa.Column('dielec_str_te_avg', sa.Float(), nullable=False),
    sa.Column('dielec_str_te_diag', sa.String(length=20), nullable=False),
    sa.Column('dielec_str_te_minus', sa.Integer(), nullable=False),
    sa.Column('acid_measure_desc', sa.String(length=20), nullable=False),
    sa.Column('acid_measure_minus', sa.Integer(), nullable=False),
    sa.Column('moisture_desc', sa.String(length=20), nullable=False),
    sa.Column('moisture_minus', sa.Integer(), nullable=False),
    sa.Column('furan_total', sa.Float(), nullable=False),
    sa.Column('furan_total_per_year', sa.Float(), nullable=False),
    sa.Column('furan_desc', sa.String(length=20), nullable=False),
    sa.Column('furan_minus', sa.Integer(), nullable=False),
    sa.Column('part_discharge_minus', sa.Integer(), nullable=False),
    sa.Column('oltc_96t_minus', sa.Integer(), nullable=False),
    sa.Column('oltc_diag', sa.String(length=20), nullable=False),
    sa.Column('oltc_minus', sa.Integer(), nullable=False),
    sa.Column('thermal_img_minus', sa.Integer(), nullable=False),
    sa.Column('noise_minus', sa.Integer(), nullable=False),
    sa.Column('first_voltage', sa.Integer(), nullable=False),
    sa.Column('first_voltage_minus', sa.Integer(), nullable=False),
    sa.Column('capa_times_load', sa.Float(), nullable=False),
    sa.Column('productivity_minus', sa.Integer(), nullable=False),
    sa.Column('fire_minus', sa.Integer(), nullable=False),
    sa.Column('fire_spread_minus', sa.Integer(), nullable=False),
    sa.Column('emerge_response_minus', sa.Integer(), nullable=False),
    sa.Column('rep_cost', sa.Float(), nullable=False),
    sa.Column('rep_cost_minus', sa.Integer(), nullable=False),
    sa.Column('rep_time', sa.Integer(), nullable=False),
    sa.Column('rep_time_minus', sa.Integer(), nullable=False),
    sa.Column('redundancy_minus', sa.Integer(), nullable=False),
    sa.Column('ato_minus', sa.Integer(), nullable=False),
    sa.Column('online_og_minus', sa.Integer(), nullable=False),
    sa.Column('offline_safety_minus', sa.Integer(), nullable=False),
    sa.Column('sec_minus', sa.Integer(), nullable=False),
    sa.Column('alarm_minus', sa.Integer(), nullable=False),
    sa.Column('winding_minus', sa.Integer(), nullable=False),
    sa.Column('prod_life_minus', sa.Integer(), nullable=False),
    sa.Column('connect_part_minus', sa.Integer(), nullable=False),
    sa.Column('temp_inc_limit_minus', sa.Integer(), nullable=False),
    sa.Column('test_reliability_minus', sa.Integer(), nullable=False),
    sa.Column('bushing_minus', sa.Integer(), nullable=False),
    sa.Column('oltc2_minus', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], ),
    sa.PrimaryKeyConstraint('equipment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transformer_score_detail')
    op.drop_table('score_snapshot')
    op.drop_table('periodic_inspection')
    op.drop_table('oil_test')
    op.drop_table('load_condition')
    op.drop_table('furan_reading')
    op.drop_table('equipment_extra_attribute')
    op.drop_table('dielectric_test')
    op.drop_table('dga_reading')
    op.drop_table('design_attribute')
    op.drop_table('equipment')
    op.drop_table('equipment_type')
    # ### end Alembic commands ###
